version: "3.9"
services:
  backend:
    build:
      context: ./backend
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    env_file:
      - .env
    ports:
      - 5000:5000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - doot_postgres:/var/lib/postgresql/data
# Names our volume
volumes:
  doot_postgres:
    driver: local
