// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: refresh-tokens.queries.sql

package db

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, user_agent)
VALUES ($1, $2)
RETURNING id, user_id, user_agent, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	UserID    int32
	UserAgent string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.UserAgent)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
